### ISSUE TITLE
 pre-trained resnet-50 model

### ISSUE THREAD

**Issue by YuanJianMing** [D-X-Y/caffe-reid#11]
你好，当我尝试使用resnet-50模型的时候程序会报错，具体描述如下：
执行： sh models/market1501/res50/train.sh --gpu 2,3
产生错误：Couldn't open /home/elitenect/datasets/model_pretrained/resnet/ResNet-50-model.caffemodel
 前面的模型都给了pre-trained model的链接，resnet-50也可以给一个么？
另外，想问您一下，您给的pre-trained model是训练前的，还是训练后的？

**Comment by D-X-Y** [comment]
pre-trained model是从Kaiming He的ResNet的project里下载的。你可以从的github上下载然后放到对应的位置。 pre-trained model是ImageNet pre-trained model
