### ISSUE TITLE
you deleted my issues？

### ISSUE THREAD

**Issue by hsqaihkl** [D-X-Y/caffe-reid#13]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by hsqaihkl** [comment]
why did you deleted my issues？

**Comment by D-X-Y** [comment]
Hi, I closed the previous issue, because I thought I have answered your question. If you need further discussion, you can re-open the previous issue. No need to open a new issue. Thanks.

**Comment by hsqaihkl** [comment]
OK，sorry . Could you tell me how to run your project in follow ? Like Layumi?

**Comment by D-X-Y** [comment]
Do you mean how to run this project on windows？

**Comment by hsqaihkl** [comment]
en,I download your project try to run it (in windows)，but I didn't konw which language you use in it. because i just use VS to complie my project in daily life ，so I don't know how to run it, but layumi also run his project in linux and he provided the step to run the project.

**Comment by hsqaihkl** [comment]
so,could you have time to provice me the step？Like layumi run his project in Linux with matlab.(I don't know matlab but I can run it)

**Comment by hsqaihkl** [comment]
And I learn your algorithm reason is that you use Caffe in it but layumi is Matconvnet which can't friendly fusion to VS。

**Comment by hsqaihkl** [comment]
so could help me？

**Comment by D-X-Y** [comment]
You can follow the guidance in README.
At first, you should use Matlab to prepare the data list. Then you can use the pre-defined script to train the model.
For running the project on VS, you should follow the official windows caffe instruction, I have no experience about running caffe on windows.

**Comment by hsqaihkl** [comment]
OK,Thanks for your help!
