### ISSUE TITLE
Resnet network .caffemodel file ?

### ISSUE THREAD

**Issue by aiaini66** [D-X-Y/caffe-reid#15]
Hello D-X-Y
  firstly, I want to thanks for your opening code  of article, it's help me a lot ,I have use your trained model to have a test. But ,I can't find the resnet model's weight file ,while named  ResNet-50-model.caffemodel . It's convenient to you to provide it for me . I just use it for the academic research. I'm looking forward your reply!  or you can  send me a  email at address :973508777@qq.com .

**Comment by D-X-Y** [comment]
You can download ResNet models from here, https://github.com/KaimingHe/deep-residual-networks#models
