### ISSUE TITLE
issues on reproducing ResNet50 of Market1501 

### ISSUE THREAD

**Issue by liuajian** [D-X-Y/caffe-reid#16]
Hell D-X-Y
Many thanks for the sharing codes. I have run through it but can not get the results that you post on the paper which rank-1 73.69 and mAP 51.48 with Gallery size 19,732. We removed the euclidean loss layer and finally have the results of rank-1 69.65 and mAP 0.42. The graph card we used is Titan XP.
It would be very kind of you to help me solve this issue. Looking forward to hearing you soon.

**Comment by liuajian** [comment]
please reply me, thanks

**Comment by layumi** [comment]
Hi @liuajian , 
Did you change the bachsize?
For Market-1501, you may try using the batchsize=32 to run the version without the verification loss. 
Sometimes you also need to adjust the learning rate a bit.
@D-X-Y may provide more suggestion from his experience later.

**Comment by D-X-Y** [comment]
In the paper, they use matlab, the different framework may cause slight performance change.

This repository is no longer maintained, and I highly recommend to use https://github.com/Cysu/open-reid or https://github.com/layumi/Person_reID_baseline_pytorch.
