### ISSUE TITLE
"caffe.LayerParameter" has no field named "reid_data_param"

### ISSUE THREAD

**Issue by hyperchris** [D-X-Y/caffe-reid#4]
When I run command "examples/market1501/training/res50_train.sh", caffe reported error "caffe.LayerParameter" has no field named "reid_data_param". 

I downloaded the market data and used generate_caffenet.py to create the needed files. I also "make" and built the caffe in the repo. Everything before training has no errors. All the needed files (e.g. images, list file, prototxt) are there. I used the .caffemodel file downloaded from https://github.com/KaimingHe/deep-residual-networks. 

After the problem occured, I looked for related solutions online. Someone said it can be caused by different caffe version. Therefore, to make sure that python can find and use the caffe in this repo, I changed the CAFFE_ROOT to the root of caffe-reid, but the problem still there. 

### Your system configuration
Operating system: Ubuntu 16.04
CUDA version (if applicable): 8.0
Python or MATLAB version (for pycaffe and matcaffe respectively): 2.7

### Full log
I0522 19:51:22.538054 17988 caffe.cpp:218] Using GPUs 0
I0522 19:51:22.628209 17988 caffe.cpp:223] GPU 0: Graphics Device
I0522 19:51:23.103369 17988 solver.cpp:44] Initializing solver from parameters: 
train_net: "models/market1501/res50/train.proto"
base_lr: 0.001
display: 100
max_iter: 18000
lr_policy: "step"
gamma: 0.1
momentum: 0.9
weight_decay: 0.0005
stepsize: 16000
snapshot: 1000
snapshot_prefix: "models/market1501/res50/snapshot/res50.full"
device_id: 0
train_state {
  level: 0
  stage: ""
}
average_loss: 25
iter_size: 4
I0522 19:51:23.103529 17988 solver.cpp:77] Creating training net from train_net file: models/market1501/res50/train.proto
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 13:19: Message type "caffe.LayerParameter" has no field named "reid_data_param".
F0522 19:51:23.103631 17988 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/market1501/res50/train.proto
*** Check failure stack trace: ***
    @     0x7f5471c625cd  google::LogMessage::Fail()
    @     0x7f5471c64433  google::LogMessage::SendToLog()
    @     0x7f5471c6215b  google::LogMessage::Flush()
    @     0x7f5471c64e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f5472354d01  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7f5472368704  caffe::Solver<>::InitTrainNet()
    @     0x7f54723699e5  caffe::Solver<>::Init()
    @     0x7f5472369cff  caffe::Solver<>::Solver()
    @     0x7f5472304d61  caffe::Creator_SGDSolver<>()
    @           0x40bd53  train()
    @           0x408470  main
    @     0x7f547094f830  __libc_start_main
    @           0x408c99  _start
    @              (nil)  (unknown)
examples/market1501/training/res50_train.sh: line 18: 17988 Aborted                 (core dumped) GLOG_log_dir=$MODEL/log $CAFFE train --gpu $gpu --solver models/market1501/res50/solver.proto --weights /home/smc/models/resnet/ResNet-50-model.caffemodel

**Comment by D-X-Y** [comment]
The training procedure does not involve the pycaffe or matcaffe.
The reid_data_param is defined in https://github.com/D-X-Y/caffe-reid/blob/master/src/caffe/proto/caffe.proto#1063
My system configuration seems the same as you, thus I do not know why..

**Comment by hyperchris** [comment]
I fixed the issue by "make clean", then "make all" and "make py". I also removed the definition of $CAFFE_ROOT in ~/.bashrc. Hope this will help.
