### ISSUE TITLE
compile re-id data layer 

### ISSUE THREAD

**Issue by yang502** [D-X-Y/caffe-reid#6]
I add the re_id_data.cpp and hpp in src/... and include/... of my own caffe ,and add the message of re_id_param in proto file.When I make all with my makefile.config file,I got the following error message.
I was wonder ,in re_id.hpp file #include <opencv2/core/core.hpp>.Is it mean that I must have already install opencv ?

=================  make all got error  ============================
In file included from src/caffe/layers/reid_data_layer.cpp:7:0:
./include/caffe/layers/reid_data_layer.hpp:23:54: error: expected template-name before ‘<’ token
 class ReidDataLayer : public ReidPrefetchingDataLayer<Dtype> {
                                                      ^
./include/caffe/layers/reid_data_layer.hpp:23:54: error: expected ‘{’ before ‘<’ token
./include/caffe/layers/reid_data_layer.hpp:23:54: error: expected unqualified-id before ‘<’ token
src/caffe/layers/reid_data_layer.cpp:14:38: error: invalid use of incomplete type ‘class caffe::ReidDataLayer<Dtype>’
 ReidDataLayer<Dtype>::~ReidDataLayer() {
                                      ^
In file included from src/caffe/layers/reid_data_layer.cpp:7:0:
./include/caffe/layers/reid_data_layer.hpp:23:7: note: declaration of ‘class caffe::ReidDataLayer<Dtype>’
 class ReidDataLayer : public ReidPrefetchingDataLayer<Dtype> {
       ^
src/caffe/layers/reid_data_layer.cpp:19:44: error: invalid use of incomplete type ‘class caffe::ReidDataLayer<Dtype>’
 unsigned int ReidDataLayer<Dtype>::RandRng() {
                                            ^
In file included from src/caffe/layers/reid_data_layer.cpp:7:0:
./include/caffe/layers/reid_data_layer.hpp:23:7: note: declaration of ‘class caffe::ReidDataLayer<Dtype>’
 class ReidDataLayer : public ReidPrefetchingDataLayer<Dtype> {
       ^
src/caffe/layers/reid_data_layer.cpp:28:38: error: invalid use of incomplete type ‘class caffe::ReidDataLayer<Dtype>’
       const vector<Blob<Dtype>*>& top) {
                                      ^
In file included from src/caffe/layers/reid_data_layer.cpp:7:0:
./include/caffe/layers/reid_data_layer.hpp:23:7: note: declaration of ‘class caffe::ReidDataLayer<Dtype>’
 class ReidDataLayer : public ReidPrefetchingDataLayer<Dtype> {
       ^
src/caffe/layers/reid_data_layer.cpp:124:39: error: variable or field ‘load_batch’ declared void
 void ReidDataLayer<Dtype>::load_batch(ReidBatch<Dtype>* batch) {
                                       ^
src/caffe/layers/reid_data_layer.cpp:124:39: error: ‘ReidBatch’ was not declared in this scope
src/caffe/layers/reid_data_layer.cpp:124:54: error: expected primary-expression before ‘>’ token
 void ReidDataLayer<Dtype>::load_batch(ReidBatch<Dtype>* batch) {
                                                      ^
src/caffe/layers/reid_data_layer.cpp:124:57: error: ‘batch’ was not declared in this scope
 void ReidDataLayer<Dtype>::load_batch(ReidBatch<Dtype>* batch) {
                                                         ^
In file included from ./include/caffe/blob.hpp:8:0,
                 from ./include/caffe/data_transformer.hpp:6,
                 from src/caffe/layers/reid_data_layer.cpp:6:
src/caffe/layers/reid_data_layer.cpp:193:19: error: explicit instantiation of ‘class caffe::ReidDataLayer<float>’ before definition of template
 INSTANTIATE_CLASS(ReidDataLayer);
                   ^
./include/caffe/common.hpp:43:18: note: in definition of macro ‘INSTANTIATE_CLASS’
   template class classname<float>; \
                  ^
src/caffe/layers/reid_data_layer.cpp:193:19: error: explicit instantiation of ‘class caffe::ReidDataLayer<double>’ before definition of template
 INSTANTIATE_CLASS(ReidDataLayer);
                   ^
./include/caffe/common.hpp:44:18: note: in definition of macro ‘INSTANTIATE_CLASS’
   template class classname<double>
                  ^
In file included from ./include/caffe/layer.hpp:10:0,
                 from ./include/caffe/layers/reid_data_layer.hpp:12,
                 from src/caffe/layers/reid_data_layer.cpp:7:
src/caffe/layers/reid_data_layer.cpp: In instantiation of ‘boost::shared_ptr<caffe::Layer<Dtype> > caffe::Creator_ReidDataLayer(const caffe::LayerParameter&) [with Dtype = float]’:
src/caffe/layers/reid_data_layer.cpp:194:1:   required from here
./include/caffe/layer_factory.hpp:135:67: error: invalid use of incomplete type ‘class caffe::ReidDataLayer<float>’
     return shared_ptr<Layer<Dtype> >(new type##Layer<Dtype>(param));           \
                                                                   ^
src/caffe/layers/reid_data_layer.cpp:194:1: note: in expansion of macro ‘REGISTER_LAYER_CLASS’
 REGISTER_LAYER_CLASS(ReidData);
 ^
In file included from src/caffe/layers/reid_data_layer.cpp:7:0:
./include/caffe/layers/reid_data_layer.hpp:23:7: note: declaration of ‘class caffe::ReidDataLayer<float>’
 class ReidDataLayer : public ReidPrefetchingDataLayer<Dtype> {
       ^
In file included from ./include/caffe/layer.hpp:10:0,
                 from ./include/caffe/layers/reid_data_layer.hpp:12,
                 from src/caffe/layers/reid_data_layer.cpp:7:
src/caffe/layers/reid_data_layer.cpp: In instantiation of ‘boost::shared_ptr<caffe::Layer<Dtype> > caffe::Creator_ReidDataLayer(const caffe::LayerParameter&) [with Dtype = double]’:
src/caffe/layers/reid_data_layer.cpp:194:1:   required from here
./include/caffe/layer_factory.hpp:135:67: error: invalid use of incomplete type ‘class caffe::ReidDataLayer<double>’
     return shared_ptr<Layer<Dtype> >(new type##Layer<Dtype>(param));           \
                                                                   ^
src/caffe/layers/reid_data_layer.cpp:194:1: note: in expansion of macro ‘REGISTER_LAYER_CLASS’
 REGISTER_LAYER_CLASS(ReidData);
 ^
In file included from src/caffe/layers/reid_data_layer.cpp:7:0:
./include/caffe/layers/reid_data_layer.hpp:23:7: note: declaration of ‘class caffe::ReidDataLayer<double>’
 class ReidDataLayer : public ReidPrefetchingDataLayer<Dtype> {
       ^
Makefile:581: recipe for target '.build_release/src/caffe/layers/reid_data_layer.o' failed

**Comment by D-X-Y** [comment]
I change many source files in this project more than re_id_data.cpp, you need to modify more files.
