### ISSUE TITLE
ReidData ?

### ISSUE THREAD

**Issue by zgplvyou** [D-X-Y/caffe-reid#8]
Thanks for your code. I am confused about your Res50-train framework. I know the framework proposed by Zhen Zhedong should be a siamese network. but the form of your network is different with the Siamese network in caffe.  So could you give us some instruction about your ReidData layer after 2018CVPR?

**Comment by D-X-Y** [comment]
Sure, I will come back after CVPR 2018 ASAP.

**Comment by D-X-Y** [comment]
@zgplvyou Hi, I randomly sample x persons in the ReID data layer as well as their corresponding positive/negative pairs. Then they are concatenated in the ReID data layer, therefore if you set batch size = 32 in the ReID data parameter, then the first dimension of ReID layer should be 64.
For siamese network, I write a PairEuclideanLayer by myself to sub the feature of one pair, and the feature are mapped into a 2-way predictions, which indicates the image in this pair is the same person or not.
