### ISSUE TITLE
I want to register re_id_data_layer into a new caffe, and complile erroe: 

### ISSUE THREAD

**Issue by liuajian** [D-X-Y/caffe-reid#9]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by liuajian** [comment]
whether the reid_data_layer compatible with a new edition of caffe? Thanks

**Comment by D-X-Y** [comment]
It requires some modifications to adapt the reid_data_layer to the lastest Caffe.
Most of the code can be directly re-used in the lastest Caffe, but you may still look into the details of reid_data_layer and base_data_layer to ensure the correctness.
